# Generated by Django 4.2.2 on 2023-06-24 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 24, 5, 54, 36, 810165, tzinfo=datetime.timezone.utc)),
        ),
    ]
